package org.first;

public class Participant {
    public String nom;
    public int numPmu;
    public int age;
    public String sexe;
    public String race;
    public String statut;
    public String oeilleres;
    public String proprietaire;
    public String entraineur;
    public String driver;
    public boolean driverChange;
    public Robe robe;
    public boolean indicateurInedit;
    public String musique;
    public int nombreCourses;
    public int nombreVictoires;
    public int nombrePlaces;
    public int nombrePlacesSecond;
    public int nombrePlacesTroisieme;
    public GainsParticipant gainsParticipant;
    public double handicapValeur;
    public String nomPere;
    public String nomMere;
    public String nomPereMere;
    public int ordreArrivee;
    public boolean jumentPleine;
    public boolean engagement;
    public int supplement;
    public int handicapPoids;
    public boolean poidsConditionMonteChange;
    public DernierRapportDirect dernierRapportDirect;
    public DernierRapportReference dernierRapportReference;
    public String urlCasaque;
    public String eleveur;
    public String allure;
    public DistanceChevalPrecedent distanceChevalPrecedent;
    public String incident;
}
